apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d3h24slzv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d3h24slzv-go 
  name: d3h24slzv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d3h24slzv-go 
